package com.pro.distribuidora.frames;

import com.pro.distribuidora.Cafe;
import com.pro.distribuidora.Orden;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;

/**
 *
 * @author JESSI
 */
public class OrdenCafeFrame extends javax.swing.JFrame {

    private Cafe cafe;
    public OrdenCafeFrame(Cafe cafe) {
        initComponents();
        tituloLabel.setText("Paquete de café " + cafe.getTipo() +" 500gr: "+ cafe.getValor());
        this.cafe = cafe;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pedidoinst = new javax.swing.ButtonGroup();
        mododepagoinst = new javax.swing.ButtonGroup();
        tituloLabel = new javax.swing.JLabel();
        cantidadLabel = new javax.swing.JLabel();
        cantidadText = new javax.swing.JTextField();
        nombreLabel = new javax.swing.JLabel();
        nombreText = new javax.swing.JTextField();
        pedidoLabel = new javax.swing.JLabel();
        localinst = new javax.swing.JRadioButton();
        nacionalinst = new javax.swing.JRadioButton();
        pagoLabel = new javax.swing.JLabel();
        creditoinst = new javax.swing.JRadioButton();
        efectivoinst = new javax.swing.JRadioButton();
        direccionLabel = new javax.swing.JLabel();
        direccioninst = new javax.swing.JTextField();
        ciudadLabel = new javax.swing.JLabel();
        ciudadinst = new javax.swing.JTextField();
        facturarButton = new javax.swing.JButton();
        ordenButton = new javax.swing.JButton();
        pedidoButton = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Completa tu orden");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloLabel.setFont(new java.awt.Font("Tekton Pro Ext", 1, 18)); // NOI18N
        tituloLabel.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(tituloLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 26, 420, -1));

        cantidadLabel.setFont(new java.awt.Font("Tekton Pro Ext", 1, 12)); // NOI18N
        cantidadLabel.setForeground(new java.awt.Color(255, 255, 255));
        cantidadLabel.setText("CANTIDAD");
        getContentPane().add(cantidadLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 74, -1, -1));

        cantidadText.setBackground(new java.awt.Color(102, 0, 0));
        cantidadText.setFont(new java.awt.Font("Tekton Pro Ext", 0, 11)); // NOI18N
        cantidadText.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(cantidadText, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 60, -1));

        nombreLabel.setFont(new java.awt.Font("Tekton Pro Ext", 0, 12)); // NOI18N
        nombreLabel.setForeground(new java.awt.Color(255, 255, 255));
        nombreLabel.setText("NOMBRE Y APELLIDO");
        getContentPane().add(nombreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, -1));

        nombreText.setBackground(new java.awt.Color(102, 0, 0));
        nombreText.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(nombreText, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 151, -1));

        pedidoLabel.setFont(new java.awt.Font("Tekton Pro Ext", 1, 12)); // NOI18N
        pedidoLabel.setForeground(new java.awt.Color(255, 255, 255));
        pedidoLabel.setText("PEDIDO ");
        getContentPane().add(pedidoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 120, -1, -1));

        localinst.setBackground(new java.awt.Color(102, 0, 0));
        pedidoinst.add(localinst);
        localinst.setFont(new java.awt.Font("Tekton Pro Ext", 0, 11)); // NOI18N
        localinst.setForeground(new java.awt.Color(255, 255, 255));
        localinst.setText("LOCAL");
        localinst.setActionCommand("local");
        getContentPane().add(localinst, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 141, -1, -1));

        nacionalinst.setBackground(new java.awt.Color(102, 0, 0));
        pedidoinst.add(nacionalinst);
        nacionalinst.setFont(new java.awt.Font("Tekton Pro Ext", 1, 11)); // NOI18N
        nacionalinst.setForeground(new java.awt.Color(255, 255, 255));
        nacionalinst.setText("NACIONAL");
        getContentPane().add(nacionalinst, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        pagoLabel.setFont(new java.awt.Font("Tekton Pro Ext", 1, 12)); // NOI18N
        pagoLabel.setForeground(new java.awt.Color(255, 255, 255));
        pagoLabel.setText("MODO DE PAGO");
        getContentPane().add(pagoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, -1));

        creditoinst.setBackground(new java.awt.Color(102, 0, 0));
        mododepagoinst.add(creditoinst);
        creditoinst.setFont(new java.awt.Font("Tekton Pro Ext", 1, 12)); // NOI18N
        creditoinst.setForeground(new java.awt.Color(255, 255, 255));
        creditoinst.setText("CREDITO");
        getContentPane().add(creditoinst, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 141, -1, -1));

        efectivoinst.setBackground(new java.awt.Color(102, 0, 0));
        mododepagoinst.add(efectivoinst);
        efectivoinst.setFont(new java.awt.Font("Tekton Pro Ext", 1, 11)); // NOI18N
        efectivoinst.setForeground(new java.awt.Color(255, 255, 255));
        efectivoinst.setText("EFECTIVO");
        getContentPane().add(efectivoinst, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 141, -1, -1));

        direccionLabel.setFont(new java.awt.Font("Tekton Pro Ext", 1, 12)); // NOI18N
        direccionLabel.setForeground(new java.awt.Color(255, 255, 255));
        direccionLabel.setText("DIRECCION");
        getContentPane().add(direccionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        direccioninst.setBackground(new java.awt.Color(102, 0, 0));
        direccioninst.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(direccioninst, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 187, 126, -1));

        ciudadLabel.setFont(new java.awt.Font("Tekton Pro Ext", 1, 12)); // NOI18N
        ciudadLabel.setForeground(new java.awt.Color(255, 255, 255));
        ciudadLabel.setText("CIUDAD");
        getContentPane().add(ciudadLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 221, -1, -1));

        ciudadinst.setBackground(new java.awt.Color(102, 0, 0));
        ciudadinst.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(ciudadinst, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 218, 126, -1));

        facturarButton.setBackground(new java.awt.Color(102, 0, 0));
        facturarButton.setFont(new java.awt.Font("Tekton Pro Ext", 1, 14)); // NOI18N
        facturarButton.setForeground(new java.awt.Color(255, 255, 255));
        facturarButton.setText("FACTURAR");
        facturarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facturarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(facturarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 130, 61));

        ordenButton.setBackground(new java.awt.Color(102, 0, 0));
        ordenButton.setFont(new java.awt.Font("Tekton Pro Ext", 1, 14)); // NOI18N
        ordenButton.setForeground(new java.awt.Color(255, 255, 255));
        ordenButton.setText("Nueva Orden");
        ordenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordenButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ordenButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 150, 30));

        pedidoButton.setBackground(new java.awt.Color(102, 0, 0));
        pedidoButton.setFont(new java.awt.Font("Tekton Pro Ext", 1, 14)); // NOI18N
        pedidoButton.setForeground(new java.awt.Color(255, 255, 255));
        pedidoButton.setText("Nuevo Pedido");
        pedidoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedidoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(pedidoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 150, 30));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ws_Coffee_Grains_1920x1200.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 330));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ordenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordenButtonActionPerformed
        cantidadText.setText("");
        nombreText.setText("");
        direccioninst.setText("");
        ciudadinst.setText("");
        pedidoinst.clearSelection();
        mododepagoinst.clearSelection();
    }//GEN-LAST:event_ordenButtonActionPerformed

    private void facturarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facturarButtonActionPerformed
        Orden orden = new Orden();
        orden.setCafe(cafe);
        orden.setCantidad(Integer.parseInt(cantidadText.getText()));
        orden.setNombres(nombreText.getText());
        orden.setPedido(getTextoRadio(pedidoinst));
        orden.setMetodoPago(getTextoRadio(mododepagoinst));
        orden.setDireccion(direccioninst.getText());
        orden.setCiudad(ciudadinst.getText());
        
        FacturaFrame facturaFrame = new FacturaFrame(orden);
        facturaFrame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_facturarButtonActionPerformed

    private void pedidoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedidoButtonActionPerformed
        Pedido g = new Pedido();
        g.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_pedidoButtonActionPerformed

    private String getTextoRadio(ButtonGroup buttonGroup) {
        for (Enumeration<AbstractButton> buttons = buttonGroup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();
            if (button.isSelected()) {
                return button.getText();
            }
        }
        return null;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cantidadLabel;
    public javax.swing.JTextField cantidadText;
    private javax.swing.JLabel ciudadLabel;
    public javax.swing.JTextField ciudadinst;
    public javax.swing.JRadioButton creditoinst;
    private javax.swing.JLabel direccionLabel;
    public javax.swing.JTextField direccioninst;
    public javax.swing.JRadioButton efectivoinst;
    public javax.swing.JButton facturarButton;
    private javax.swing.JLabel fondo;
    public javax.swing.JRadioButton localinst;
    private javax.swing.ButtonGroup mododepagoinst;
    private javax.swing.JRadioButton nacionalinst;
    private javax.swing.JLabel nombreLabel;
    public javax.swing.JTextField nombreText;
    public javax.swing.JButton ordenButton;
    private javax.swing.JLabel pagoLabel;
    public javax.swing.JButton pedidoButton;
    private javax.swing.JLabel pedidoLabel;
    private javax.swing.ButtonGroup pedidoinst;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables
}
