package com.pro.distribuidora.frames;

import com.pro.distribuidora.Cafe;

/**
 *
 * @author JESSI
 */
public class Pedido extends javax.swing.JFrame {

    private OrdenCafeFrame cafeFrame;
    public Pedido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        granuladoButton = new javax.swing.JButton();
        instantaneoButton = new javax.swing.JButton();
        expressoButton = new javax.swing.JButton();
        fondo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Selecciona tu café");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tekton Pro Ext", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setText("¿ Qué deseas pedir?");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 240, 60));

        jLabel2.setFont(new java.awt.Font("Tekton Pro Ext", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 0));
        jLabel2.setText("Café");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, -1));

        granuladoButton.setBackground(new java.awt.Color(102, 0, 0));
        granuladoButton.setFont(new java.awt.Font("Tekton Pro Ext", 1, 11)); // NOI18N
        granuladoButton.setForeground(new java.awt.Color(255, 255, 255));
        granuladoButton.setText("Granulado");
        granuladoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                granuladoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(granuladoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, -1, -1));

        instantaneoButton.setBackground(new java.awt.Color(102, 0, 0));
        instantaneoButton.setFont(new java.awt.Font("Tekton Pro Ext", 1, 11)); // NOI18N
        instantaneoButton.setForeground(new java.awt.Color(255, 255, 255));
        instantaneoButton.setText("Instantaneo");
        instantaneoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instantaneoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(instantaneoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));

        expressoButton.setBackground(new java.awt.Color(102, 0, 0));
        expressoButton.setFont(new java.awt.Font("Tekton Pro Ext", 1, 11)); // NOI18N
        expressoButton.setForeground(new java.awt.Color(255, 255, 255));
        expressoButton.setText("Expresso");
        expressoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expressoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(expressoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, -1));

        fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/superb-coffee-brown-wallpaper-3.jpg"))); // NOI18N
        getContentPane().add(fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void granuladoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_granuladoButtonActionPerformed
        Cafe granulado = new Cafe("Granulado", 30000);
        cafeFrame = new OrdenCafeFrame(granulado);
        cafeFrame.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_granuladoButtonActionPerformed

    private void instantaneoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instantaneoButtonActionPerformed
        Cafe instantaneo = new Cafe("Instantaneo", 20000);
        cafeFrame = new OrdenCafeFrame(instantaneo);
        cafeFrame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_instantaneoButtonActionPerformed

    private void expressoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expressoButtonActionPerformed
        Cafe expresso = new Cafe("Expresso", 40000);
        cafeFrame = new OrdenCafeFrame(expresso);
        cafeFrame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_expressoButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton expressoButton;
    private javax.swing.JLabel fondo2;
    private javax.swing.JButton granuladoButton;
    private javax.swing.JButton instantaneoButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
